[package]
name = "termite-server"
version = "0.1.0"
edition = "2024"

[dependencies]
termite-core = { path = "../termite-core" }
tokio = { version = "1", features = ["full"] }
axum = "0.8.8"
tower = "0.5.3"
